language: node_js

node_js:
  - node

env:
  global: PATH=/opt/python/3.7.1/bin:$PATH

notifications:
  email: false
  slack: nautilus27:HZhDaJlZZK80zNaPCmueIiWk

# cache some files for faster builds
cache:
  yarn: true
  directories:
    - node_modules

# on PRs and merges to master and prod run tests and build the app
script:
  - yarn test
  - python3 -VV
  - pip -V

before_deploy:
  - "echo 'Deploying to nautilusdev.com s3 bucket'"
  # install aws cli
  - python3 -m pip install --user awscli
  # Append exe location to our PATH
  - export PATH=$PATH:$HOME/.local/bin
  # build electron application
  - yarn package-all

deploy:
  process: script
  skip_cleanup: true
  on: master
  script: sh $TRAVIS_BUILD_DIR/scripts/deploy.sh

# only run this script on pull requests and merges into
# the 'master' branches
branches:
  only:
    - master
