language: node_js

node_js:
  - '11.6.0'

env:
  global: PATH=/opt/python/3.7.1/bin:$PATH

# Always run two parallel builds: one on mac and one on linux
# the linux build will use wine to be able to build windows and
# linux apps
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: '11.6.0'
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      dist: trusty
      sudo: required
      services: docker
      language: generic

notifications:
  email: false
  slack: nautilus27:HZhDaJlZZK80zNaPCmueIiWk

# cache some files for faster builds
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

# on PRs and merges to master and prod run tests and build the app
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn test"
    else
      yarn test
    fi
  - python3 -VV
  - pip -V

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

before_deploy:
  - "echo 'Deploying to nautilusdev.com s3 bucket'"
  - python3 -m pip install --user awscli
  - export PATH=/opt/python/3.7.1/bin:$PATH
  - yarn package-all

deploy:
  process: script
  skip_cleanup: true
  on: master
  script: sh $TRAVIS_BUILD_DIR/scripts/deploy.sh

# only run this script on pull requests and merges into
# the 'master' branches
branches:
  only:
    - master
