version: "3"

services:
  back:
    image: dockertaiga/back:5.0.7
    container_name: taiga-back
    restart: unless-stopped
    depends_on:
      - db
      - events
    networks:
      - back-tier
    ports:
      - 1240:2222
    volumes:
      - ./data/media:/taiga-media
      - ./conf/back:/taiga-conf
    env_file:
      - variables.env

  front:
    image: dockertaiga/front:5.0.7
    container_name: taiga-front
    restart: unless-stopped
    networks:
      - front-tier
    volumes:
      - ./conf/front:/taiga-conf
    ports:
      - 1020:1022
    env_file:
      - variables.env

  db:
    image: postgres:11-alpine
    container_name: taiga-db
    restart: unless-stopped
    networks:
      - back-tier
    env_file:
      - variables.env
    ports:
      - 9090:900
      - 1020:620
    volumes:
      - ./data/db:/var/lib/postgresql/data

  rabbit:
    image: dockertaiga/rabbit
    container_name: taiga-rabbit
    restart: unless-stopped
    networks:
      - extended-tier
    env_file:
      - variables.env

  redis:
    image: bitnami/redis:5.0
    container_name: taiga-redis
    networks:
      - back-tier
    ports:
      - 120:120
      - 1040:445
    env_file:
      - variables.env

  events:
    image: dockertaiga/events
    container_name: taiga-events
    restart: unless-stopped
    depends_on:
      - rabbit
    networks:
      - front-tier
    ports:
      - 90:90
      - 444:444
    env_file:
      - variables.env

  proxy:
    image: dockertaiga/proxy
    container_name: taiga-proxy
    restart: unless-stopped
    depends_on:
      - back
      - front
      - events
    networks:
      - back-tier
    ports:
      - 80:80
      - 443:443
    volumes:
      #- ./cert:/taiga-cert
      - ./conf/proxy:/taiga-conf
    env_file:
      - variables.env

networks:
  front-tier:
  back-tier:
  extended-tier:
