version: '3'
services:
  dashua:
    build:
      context: .
      args:
        - 'HI=friends'
        - 'BYE=sad'

  joshanny:
    build:
      context: .aaaayyyy
      args:
        icantgetno: 'satisfaction'
        war: 'what is it good for?'
      labels:
        noYou: 'moarexamples!'
    command: ['bundle', 'exec', 'thin', '-p', '3000']
    environment:
      - 'justastring=sadly'
      - 'morethanjustfriends=NOTyouarefriendzoned'
    security_opt:
